---
#saltminion_prep
- name: See if dependency directory exists
  stat:
    path: /var/lib/containers
  register: var_lib_containers

- name: Create dependency directory
  file:
    path: /var/lib/containers
    state: directory
    owner: root
    group: root
    mode: 0770
  when: var_lib_containers.stat.exists == False
  register: var_lib_containers_created

- name: See if root/.ssh directory exists
  stat:
    path: /root/.ssh
  register: root_ssh

- name: Create root .ssh dir
  file:
    path: /root/.ssh
    state: directory
    mode: 0755
  when: root_ssh.stat.exists == False

- name: Deploy git file
  copy:
    src: "{{inventory_dir}}/srv_certs/{{ item.file }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
   - { file: 'id_rsa_git', dest: '/root/.ssh/id_rsa', owner: root, group: root, mode: 600 }
